---
- name: Install postgresql
  package:
    name: "postgresql"
    state: present

- name: Install postgresql-contrib
  package:
    name: "postgresql-contrib"
    state: present

- name: Start postgresql service
  systemd:
    name: postgresql.service
    daemon_reload: yes
    state: started
    enabled: yes

- name: Install psycopg2-binary python package
  ansible.builtin.pip:
    name: psycopg2-binary==2.9.5 