---
- name: Create a database named "test"
  community.postgresql.postgresql_db:
    name: test

- name: Create user named "poc" with access to "test" database
  community.postgresql.postgresql_user:
    db: test
    name: poc
    password: dummy_pass
    comment: This is a test user

- name: GRANT ALL PRIVILEGES ON DATABASE "test" TO "poc"
  community.postgresql.postgresql_privs:
    db: test
    privs: ALL
    type: database
    role: poc