---
- name: Install software-properties-common
  package:
    name: "software-properties-common"
    state: present

- name: Add deadsnakes repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install python3.8
  package:
    name: "python3.8"
    state: present

- name: Install python3-pip
  package:
    name: "python3-pip"
    state: present
