---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
     - import_tasks: base_vm_config/pam_pwquality.yml
     - import_tasks: base_vm_config/user_and_group.yml
     - import_tasks: postgresql/install.yml
  handlers:
     - import_tasks: handlers/restart_ssh.yml
