---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars:
      neo4j_password: "password123"
  tasks:
     - import_tasks: base_vm_config/pam_pwquality.yml
     - import_tasks: base_vm_config/user_and_group.yml
     - import_tasks: base_vm_config/misc_installs.yml
     - import_tasks: python/install.yml
     - import_tasks: neo4j/install.yml
  handlers:
     - import_tasks: handlers/restart_ssh.yml


